function comparison = buildSite1OscroftFairComparison(options)
arguments
    options.nBootstraps (1,1) double {mustBeInteger, mustBePositive} = 1000
    options.randomSeed (1,1) double {mustBeInteger, mustBeFinite} = 0
    options.scoreStride (1,1) double {mustBeInteger, mustBePositive} = 6
    options.oldDof (1,1) double {mustBeInteger, mustBePositive} = 4
    options.oldModelIndex (1,1) double {mustBeInteger, mustBeMember(options.oldModelIndex, 1:7)} = 3
    options.psiS (1,3) double {mustBeInteger, mustBeNonnegative} = [2 2 3]
    options.fastS (1,1) double {mustBeInteger, mustBeNonnegative} = 3
    options.mesoscaleConstraint {mustBeTextScalar, mustBeMember(options.mesoscaleConstraint, ["none", "zeroVorticity", "zeroStrain"])} = "zeroVorticity"
    options.shouldLoadPublishedBaseline (1,1) logical = true
    options.shouldUseCache (1,1) logical = true
    options.shouldRefreshCache (1,1) logical = false
    options.cacheDirectory {mustBeTextScalar} = ""
    options.displaySummary (1,1) logical = true
end

scriptDir = fileparts(mfilename("fullpath"));
cachePath = "";
if options.shouldUseCache
    cachePath = site1OscroftFairComparisonCachePath(scriptDir, options);
    if ~options.shouldRefreshCache
        comparison = loadCachedSite1OscroftFairComparison(cachePath, options);
        if ~isempty(comparison)
            comparison.cacheInfo.wasLoadedFromCache = true;
            comparison.cacheInfo.cachePath = string(cachePath);
            if options.displaySummary
                displayComparisonSummary(comparison);
            end
            return
        end
    end
end

site = loadSite1ComparisonInputs(scriptDir, options.scoreStride);
sharedBootstrapIndices = deterministicBootstrapIndices(site.nDrifters, options.nBootstraps, options.randomSeed);

oldShared = buildLinearVelocityFieldEnsemble( ...
    site, ...
    sharedBootstrapIndices, ...
    dof=options.oldDof, ...
    modelIndex=options.oldModelIndex, ...
    historicalScores=[]);
newShared = buildGriddedStreamfunctionEnsemble( ...
    site, ...
    sharedBootstrapIndices, ...
    psiS=options.psiS, ...
    fastS=options.fastS, ...
    mesoscaleConstraint=options.mesoscaleConstraint);

publishedBaseline = struct("available", false);
stageDiagnostics = repmat(emptyStageDiagnostic(), 0, 1);
if options.shouldLoadPublishedBaseline
    publishedBaseline = loadPublishedBaseline( ...
        scriptDir, ...
        site, ...
        dof=options.oldDof, ...
        modelIndex=options.oldModelIndex, ...
        psiS=options.psiS, ...
        fastS=options.fastS, ...
        mesoscaleConstraint=options.mesoscaleConstraint);
    if publishedBaseline.available
        stageDiagnostics(end + 1) = stageDiagnosticFromRankedSeries( ... %#ok<AGROW>
            "Current published comparison", ...
            "published display", ...
            publishedBaseline.old.displaySeries, ...
            publishedBaseline.new.displaySeries, ...
            publishedBaseline.old.scores.historical, ...
            publishedBaseline.new.scores.current);
        stageDiagnostics(end + 1) = stageDiagnosticFromRankedSeries( ... %#ok<AGROW>
            "Variable-space aligned comparison", ...
            "published aligned", ...
            publishedBaseline.old.commonSeries, ...
            publishedBaseline.new.commonSeries, ...
            publishedBaseline.old.scores.historical, ...
            publishedBaseline.new.scores.current);
    end
end

stageDiagnostics(end + 1) = stageDiagnosticFromRankedSeries( ... %#ok<AGROW>
    "Shared-resample comparison", ...
    "shared draws", ...
    oldShared.commonSeries, ...
    newShared.commonSeries, ...
    oldShared.scores.historical, ...
    newShared.scores.current);
stageDiagnostics(end + 1) = stageDiagnosticFromRankedSeries( ... %#ok<AGROW>
    "Shared-score comparison", ...
    "shared draws + common score", ...
    oldShared.commonSeries, ...
    newShared.commonSeries, ...
    oldShared.scores.common, ...
    newShared.scores.common);

comparison = struct( ...
    "settings", struct( ...
        "nBootstraps", options.nBootstraps, ...
        "randomSeed", options.randomSeed, ...
        "scoreStride", options.scoreStride, ...
        "oldDof", options.oldDof, ...
        "oldModelIndex", options.oldModelIndex, ...
        "psiS", options.psiS, ...
        "fastS", options.fastS, ...
        "mesoscaleConstraint", string(options.mesoscaleConstraint), ...
        "shouldLoadPublishedBaseline", options.shouldLoadPublishedBaseline), ...
    "site", site, ...
    "sharedBootstrapIndices", sharedBootstrapIndices, ...
    "old", struct("shared", oldShared), ...
    "new", struct("shared", newShared), ...
    "publishedBaseline", publishedBaseline, ...
    "stageDiagnostics", stageDiagnostics, ...
    "fullFitDiagnostic", seriesDiagnostic(oldShared.fullCommonSeries, newShared.fullCommonSeries), ...
    "matchedSharedBootstrapDiagnostic", matchedBootstrapDiagnostic(oldShared.commonSeries, newShared.commonSeries), ...
    "cacheInfo", struct( ...
        "cacheVersion", site1OscroftFairComparisonCacheVersion(), ...
        "cachePath", string(cachePath), ...
        "wasLoadedFromCache", false, ...
        "siteDataModifiedDatenum", siteDataModifiedDatenum(site.dataPath)));

if options.shouldUseCache
    cacheDir = fileparts(cachePath);
    if exist(cacheDir, "dir") == 0
        mkdir(cacheDir);
    end
    save(cachePath, "comparison");
end

if options.displaySummary
    displayComparisonSummary(comparison);
end
end

function cachePath = site1OscroftFairComparisonCachePath(scriptDir, options)
cacheDirectory = string(options.cacheDirectory);
if strlength(cacheDirectory) == 0
    cacheDirectory = string(fullfile(scriptDir, "CacheData"));
end

cachePath = fullfile(cacheDirectory, site1OscroftFairComparisonCacheFilename( ...
    nBootstraps=options.nBootstraps, ...
    randomSeed=options.randomSeed, ...
    scoreStride=options.scoreStride, ...
    oldDof=options.oldDof, ...
    oldModelIndex=options.oldModelIndex, ...
    psiS=options.psiS, ...
    fastS=options.fastS, ...
    mesoscaleConstraint=options.mesoscaleConstraint, ...
    shouldLoadPublishedBaseline=options.shouldLoadPublishedBaseline));
end

function comparison = loadCachedSite1OscroftFairComparison(cachePath, options)
comparison = [];
if ~isfile(cachePath)
    return
end

try
    fileData = load(cachePath, "comparison");
catch
    return
end

if ~isfield(fileData, "comparison") || ~isValidCachedSite1OscroftFairComparison(fileData.comparison, options)
    return
end

comparison = fileData.comparison;
end

function tf = isValidCachedSite1OscroftFairComparison(comparison, options)
tf = isstruct(comparison) && ...
    isfield(comparison, "settings") && ...
    isfield(comparison, "site") && ...
    isfield(comparison, "old") && ...
    isfield(comparison, "new") && ...
    isfield(comparison, "stageDiagnostics") && ...
    isfield(comparison, "fullFitDiagnostic") && ...
    isfield(comparison, "matchedSharedBootstrapDiagnostic") && ...
    isfield(comparison, "cacheInfo");
if ~tf
    return
end

tf = hasMatchingSetting(comparison.settings, "nBootstraps", options.nBootstraps) && ...
    hasMatchingSetting(comparison.settings, "randomSeed", options.randomSeed) && ...
    hasMatchingSetting(comparison.settings, "scoreStride", options.scoreStride) && ...
    hasMatchingSetting(comparison.settings, "oldDof", options.oldDof) && ...
    hasMatchingSetting(comparison.settings, "oldModelIndex", options.oldModelIndex) && ...
    hasMatchingSetting(comparison.settings, "psiS", options.psiS) && ...
    hasMatchingSetting(comparison.settings, "fastS", options.fastS) && ...
    hasMatchingSetting(comparison.settings, "mesoscaleConstraint", string(options.mesoscaleConstraint)) && ...
    hasMatchingSetting(comparison.settings, "shouldLoadPublishedBaseline", options.shouldLoadPublishedBaseline) && ...
    hasMatchingSetting(comparison.cacheInfo, "cacheVersion", site1OscroftFairComparisonCacheVersion()) && ...
    isfield(comparison.cacheInfo, "siteDataModifiedDatenum") && ...
    isfield(comparison.site, "dataPath") && ...
    isfield(comparison.site, "queryTimes") && ...
    ~isempty(comparison.site.queryTimes);
if ~tf
    return
end

tf = abs(siteDataModifiedDatenum(comparison.site.dataPath) - comparison.cacheInfo.siteDataModifiedDatenum) <= 1e-12;
end

function tf = hasMatchingSetting(settings, fieldName, expectedValue)
tf = isfield(settings, fieldName) && isequal(settings.(fieldName), expectedValue);
end

function value = siteDataModifiedDatenum(dataPath)
if ~isfile(dataPath)
    value = NaN;
    return
end

fileInfo = dir(dataPath);
value = fileInfo.datenum;
end

function value = site1OscroftFairComparisonCacheVersion()
value = 1;
end

function site = loadSite1ComparisonInputs(scriptDir, scoreStride)
dataPath = fullfile(scriptDir, "..", "ExampleData", "LatMix2011", "smoothedGriddedRho1Drifters.mat");
if ~isfile(dataPath)
    error("GriddedStreamfunction:MissingExampleData", ...
        "Expected local example data at %s.", dataPath);
end

siteData = load(dataPath);
t = reshape(siteData.t, [], 1);
x = siteData.x(:, 1:(end - 1));
y = siteData.y(:, 1:(end - 1));
nDrifters = size(x, 2);
trajectories = TrajectorySpline.empty(0, 1);
for iDrifter = 1:nDrifters
    trajectories(end + 1, 1) = TrajectorySpline.fromData(t, x(:, iDrifter), y(:, iDrifter), S=3); %#ok<AGROW>
end

f0 = 2 * 7.2921e-5 * sin(siteData.lat0*pi/180);
queryTimes = t;
scoreIndices = 1:scoreStride:numel(queryTimes);
scoreTimes = queryTimes(scoreIndices);

site = struct( ...
    "dataPath", dataPath, ...
    "t", t, ...
    "x", x, ...
    "y", y, ...
    "trajectories", trajectories, ...
    "nDrifters", nDrifters, ...
    "f0", f0, ...
    "queryTimes", queryTimes, ...
    "scoreTimes", scoreTimes, ...
    "scoreIndices", scoreIndices, ...
    "scoreStride", scoreStride);
end

function bootstrapIndices = deterministicBootstrapIndices(nDrifters, nBootstraps, randomSeed)
originalRng = rng;
cleanupRng = onCleanup(@() rng(originalRng));
rng(randomSeed);
bootstrapIndices = randi(nDrifters, nBootstraps, nDrifters);
end

function ensemble = buildLinearVelocityFieldEnsemble(site, bootstrapIndices, options)
arguments
    site struct
    bootstrapIndices {mustBeNumeric, mustBeReal, mustBeFinite}
    options.dof (1,1) double {mustBeInteger, mustBePositive}
    options.modelIndex (1,1) double {mustBeInteger, mustBeMember(options.modelIndex, 1:7)} = 3
    options.historicalScores = []
end

parametersToEstimate = modelParametersForIndex(options.modelIndex);
[fullParameters, ~] = EstimateLinearVelocityFieldParameters(site.x, site.y, site.t, parametersToEstimate, options.dof);
fullOldSummary = linearSummaryFromParameters(fullParameters);
fullCommonSummary = transformLinearSummaryToCommonSpace( ...
    fullOldSummary, mean(site.x, 2), mean(site.y, 2));

nTime = numel(site.queryTimes);
nBootstraps = size(bootstrapIndices, 1);
oldSummary = emptyLinearSummary(nTime, nBootstraps);
mx = zeros(nTime, nBootstraps);
my = zeros(nTime, nBootstraps);

for iBootstrap = 1:nBootstraps
    sampledIndices = bootstrapIndices(iBootstrap, :);
    xSub = site.x(:, sampledIndices);
    ySub = site.y(:, sampledIndices);
    parameters = EstimateLinearVelocityFieldParameters(xSub, ySub, site.t, parametersToEstimate, options.dof);
    summary = linearSummaryFromParameters(parameters);
    oldSummary.u0(:, iBootstrap) = summary.u0;
    oldSummary.v0(:, iBootstrap) = summary.v0;
    oldSummary.sigma_n(:, iBootstrap) = summary.sigma_n;
    oldSummary.sigma_s(:, iBootstrap) = summary.sigma_s;
    oldSummary.zeta(:, iBootstrap) = summary.zeta;
    oldSummary.delta(:, iBootstrap) = summary.delta;
    mx(:, iBootstrap) = mean(xSub, 2);
    my(:, iBootstrap) = mean(ySub, 2);
end

commonSummary = transformLinearSummaryToCommonSpace(oldSummary, mx, my);
if isempty(options.historicalScores)
    historicalScores = EstimateSolutionLikelihoodFromBootstraps(oldSummary, parametersToEstimate, site.scoreStride);
else
    historicalScores = reshape(options.historicalScores, 1, []);
end
commonScores = computeComparisonConsensusScores(commonSummary, site.scoreIndices, "zeroVorticity");

ensemble = struct( ...
    "bootstrapIndices", bootstrapIndices, ...
    "parametersToEstimate", parametersToEstimate, ...
    "fullOldSummary", fullOldSummary, ...
    "fullCommonSummary", fullCommonSummary, ...
    "oldSummary", oldSummary, ...
    "commonSummary", commonSummary, ...
    "fullDisplaySeries", displaySeriesFromLinearOldSummary(fullOldSummary), ...
    "displaySeries", displaySeriesFromLinearOldSummary(oldSummary), ...
    "fullCommonSeries", commonSeriesFromSummary(fullCommonSummary, fullCommonSummary), ...
    "commonSeries", commonSeriesFromSummary(commonSummary, fullCommonSummary), ...
    "scores", struct( ...
        "historical", historicalScores, ...
        "current", historicalScores, ...
        "common", commonScores.joint, ...
        "commonComponents", commonScores));
end

function ensemble = buildGriddedStreamfunctionEnsemble(site, bootstrapIndices, options)
arguments
    site struct
    bootstrapIndices {mustBeNumeric, mustBeReal, mustBeFinite}
    options.psiS (1,3) double {mustBeInteger, mustBeNonnegative}
    options.fastS (1,1) double {mustBeInteger, mustBeNonnegative}
    options.mesoscaleConstraint {mustBeTextScalar, mustBeMember(options.mesoscaleConstraint, ["none", "zeroVorticity", "zeroStrain"])}
end

fitOptions = struct( ...
    "psiS", options.psiS, ...
    "fastS", options.fastS, ...
    "mesoscaleConstraint", string(options.mesoscaleConstraint), ...
    "buildDecomposition", false);
fitArguments = namedargs2cell(fitOptions);

fullFit = GriddedStreamfunction(site.trajectories, fitArguments{:});
fullSummary = summaryFromGriddedFit(fullFit, site.queryTimes);

nTime = numel(site.queryTimes);
nBootstraps = size(bootstrapIndices, 1);
summary = emptyCommonSummary(nTime, nBootstraps);

for iBootstrap = 1:nBootstraps
    sampledTrajectories = reshape(site.trajectories(bootstrapIndices(iBootstrap, :)), [], 1);
    fit = GriddedStreamfunction(sampledTrajectories, fitArguments{:});
    bootstrapSummary = summaryFromGriddedFit(fit, site.queryTimes);
    summary.uCenter(:, iBootstrap) = bootstrapSummary.uCenter;
    summary.vCenter(:, iBootstrap) = bootstrapSummary.vCenter;
    summary.sigma_n(:, iBootstrap) = bootstrapSummary.sigma_n;
    summary.sigma_s(:, iBootstrap) = bootstrapSummary.sigma_s;
    summary.zeta(:, iBootstrap) = bootstrapSummary.zeta;
end

currentScores = computeComparisonConsensusScores(summary, site.scoreIndices, options.mesoscaleConstraint);
ensemble = struct( ...
    "bootstrapIndices", bootstrapIndices, ...
    "fullSummary", fullSummary, ...
    "fullCommonSummary", fullSummary, ...
    "summary", summary, ...
    "commonSummary", summary, ...
    "fullDisplaySeries", displaySeriesFromGriddedSummary(fullSummary), ...
    "displaySeries", displaySeriesFromGriddedSummary(summary), ...
    "fullCommonSeries", commonSeriesFromSummary(fullSummary, fullSummary), ...
    "commonSeries", commonSeriesFromSummary(summary, fullSummary), ...
    "scores", struct( ...
        "current", currentScores.joint, ...
        "common", currentScores.joint, ...
        "commonComponents", currentScores));
end

function publishedBaseline = loadPublishedBaseline(scriptDir, site, options)
arguments
    scriptDir {mustBeTextScalar}
    site struct
    options.dof (1,1) double {mustBeInteger, mustBePositive}
    options.modelIndex (1,1) double {mustBeInteger, mustBeMember(options.modelIndex, 1:7)}
    options.psiS (1,3) double {mustBeInteger, mustBeNonnegative}
    options.fastS (1,1) double {mustBeInteger, mustBeNonnegative}
    options.mesoscaleConstraint {mustBeTextScalar, mustBeMember(options.mesoscaleConstraint, ["none", "zeroVorticity", "zeroStrain"])}
end

oldBootstrapPath = fullfile( ...
    scriptDir, ...
    "..", "LinearVelocityField", "Examples", "FluidsPaperCaseStudy", "BootstrapData", ...
    sprintf("Rho1DrifterSplineFits1000_dof%d.mat", options.dof));
if ~isfile(oldBootstrapPath)
    publishedBaseline = struct("available", false, "missingPath", oldBootstrapPath);
    return
end

oldData = load(oldBootstrapPath, "bootstraps", "drifterPermutations");
oldBootstrap = oldData.bootstraps{options.modelIndex};
oldFullParameters = EstimateLinearVelocityFieldParameters( ...
    site.x, site.y, site.t, modelParametersForIndex(options.modelIndex), options.dof);
oldFullSummary = linearSummaryFromParameters(oldFullParameters);
oldCommonSummary = transformLinearSummaryToCommonSpace(oldBootstrap, bootstrapCenterMean(site.x, oldData.drifterPermutations), bootstrapCenterMean(site.y, oldData.drifterPermutations));
oldCommonScores = computeComparisonConsensusScores(oldCommonSummary, site.scoreIndices, "zeroVorticity");
oldEnsemble = struct( ...
    "bootstrapIndices", oldData.drifterPermutations, ...
    "fullOldSummary", oldFullSummary, ...
    "fullCommonSummary", transformLinearSummaryToCommonSpace(oldFullSummary, mean(site.x, 2), mean(site.y, 2)), ...
    "oldSummary", oldBootstrap, ...
    "commonSummary", oldCommonSummary, ...
    "fullDisplaySeries", displaySeriesFromLinearOldSummary(oldFullSummary), ...
    "displaySeries", displaySeriesFromLinearOldSummary(oldBootstrap), ...
    "fullCommonSeries", commonSeriesFromSummary( ...
        transformLinearSummaryToCommonSpace(oldFullSummary, mean(site.x, 2), mean(site.y, 2)), ...
        transformLinearSummaryToCommonSpace(oldFullSummary, mean(site.x, 2), mean(site.y, 2))), ...
    "commonSeries", commonSeriesFromSummary(oldCommonSummary, transformLinearSummaryToCommonSpace(oldFullSummary, mean(site.x, 2), mean(site.y, 2))), ...
    "scores", struct( ...
        "historical", reshape(oldBootstrap.jointlikelihood, 1, []), ...
        "current", reshape(oldBootstrap.jointlikelihood, 1, []), ...
        "common", oldCommonScores.joint, ...
        "commonComponents", oldCommonScores));

newBootstrap = loadOrBuildPublishedGriddedBootstrap( ...
    scriptDir, ...
    site.trajectories, ...
    nBootstraps=1000, ...
    randomSeed=0, ...
    scoreStride=site.scoreStride, ...
    psiS=options.psiS, ...
    fastS=options.fastS, ...
    mesoscaleConstraint=options.mesoscaleConstraint);
if ~isequal(newBootstrap.queryTimes, site.queryTimes) || ~isequal(newBootstrap.scoreTimes, site.scoreTimes)
    error("GriddedStreamfunction:PublishedBootstrapTimeMismatch", ...
        "Published bootstrap query/score times do not match the Site 1 comparison times.");
end

newCommonScores = computeComparisonConsensusScores(newBootstrap.summary, site.scoreIndices, options.mesoscaleConstraint);
newEnsemble = struct( ...
    "bootstrapIndices", newBootstrap.bootstrapIndices, ...
    "fullSummary", newBootstrap.fullSummary, ...
    "fullCommonSummary", newBootstrap.fullSummary, ...
    "summary", newBootstrap.summary, ...
    "commonSummary", newBootstrap.summary, ...
    "fullDisplaySeries", displaySeriesFromGriddedSummary(newBootstrap.fullSummary), ...
    "displaySeries", displaySeriesFromGriddedSummary(newBootstrap.summary), ...
    "fullCommonSeries", commonSeriesFromSummary(newBootstrap.fullSummary, newBootstrap.fullSummary), ...
    "commonSeries", commonSeriesFromSummary(newBootstrap.summary, newBootstrap.fullSummary), ...
    "scores", struct( ...
        "current", newBootstrap.scores.joint, ...
        "common", newCommonScores.joint, ...
        "commonComponents", newCommonScores));

publishedBaseline = struct( ...
    "available", true, ...
    "old", oldEnsemble, ...
    "new", newEnsemble, ...
    "paths", struct("oldBootstrapPath", oldBootstrapPath));
end

function summary = linearSummaryFromParameters(parameters)
summary = struct( ...
    "u0", reshape(parameters.u0, [], 1), ...
    "v0", reshape(parameters.v0, [], 1), ...
    "sigma_n", reshape(parameters.sigma_n, [], 1), ...
    "sigma_s", reshape(parameters.sigma_s, [], 1), ...
    "zeta", reshape(parameters.zeta, [], 1), ...
    "delta", reshape(parameters.delta, [], 1));
end

function commonSummary = transformLinearSummaryToCommonSpace(summary, mx, my)
mx = reshapeLike(mx, summary.u0);
my = reshapeLike(my, summary.v0);
commonSummary = struct( ...
    "uCenter", summary.u0 + 0.5 * (summary.sigma_n + summary.delta) .* mx + 0.5 * (summary.sigma_s - summary.zeta) .* my, ...
    "vCenter", summary.v0 + 0.5 * (summary.sigma_s + summary.zeta) .* mx + 0.5 * (summary.delta - summary.sigma_n) .* my, ...
    "sigma_n", summary.sigma_n, ...
    "sigma_s", summary.sigma_s, ...
    "zeta", summary.zeta);
end

function values = reshapeLike(values, reference)
if isequal(size(values), size(reference))
    return
end

if isvector(values) && size(reference, 1) == numel(values)
    values = repmat(reshape(values, [], 1), 1, size(reference, 2));
    return
end

error("GriddedStreamfunction:ComparisonShapeMismatch", ...
    "Values with size %s cannot be expanded to match reference size %s.", ...
    mat2str(size(values)), mat2str(size(reference)));
end

function centers = bootstrapCenterMean(values, bootstrapIndices)
nTime = size(values, 1);
nBootstraps = size(bootstrapIndices, 1);
centers = zeros(nTime, nBootstraps);
for iBootstrap = 1:nBootstraps
    centers(:, iBootstrap) = mean(values(:, bootstrapIndices(iBootstrap, :)), 2);
end
end

function summary = summaryFromGriddedFit(fit, queryTimes)
mx = reshape(fit.centerOfMassTrajectory.x(queryTimes), [], 1);
my = reshape(fit.centerOfMassTrajectory.y(queryTimes), [], 1);
summary = struct( ...
    "uCenter", reshape(fit.uMesoscale(queryTimes, mx, my), [], 1), ...
    "vCenter", reshape(fit.vMesoscale(queryTimes, mx, my), [], 1), ...
    "sigma_n", reshape(fit.sigma_n(queryTimes, mx, my), [], 1), ...
    "sigma_s", reshape(fit.sigma_s(queryTimes, mx, my), [], 1), ...
    "zeta", reshape(fit.zeta(queryTimes, mx, my), [], 1));
end

function series = displaySeriesFromLinearOldSummary(summary)
series = struct( ...
    "u", summary.u0, ...
    "v", summary.v0, ...
    "sigma_n", summary.sigma_n, ...
    "sigma_s", summary.sigma_s, ...
    "theta", atan2(summary.sigma_s, summary.sigma_n) * 90/pi);
end

function series = displaySeriesFromGriddedSummary(summary)
series = struct( ...
    "u", summary.uCenter, ...
    "v", summary.vCenter, ...
    "sigma_n", summary.sigma_n, ...
    "sigma_s", summary.sigma_s, ...
    "theta", GriddedStreamfunction.visualPrincipalStrainAngle(summary.sigma_n, summary.sigma_s));
end

function series = commonSeriesFromSummary(summary, referenceSummary)
series = struct( ...
    "u", summary.uCenter, ...
    "v", summary.vCenter, ...
    "sigma_n", summary.sigma_n, ...
    "sigma_s", summary.sigma_s, ...
    "theta", alignPrincipalStrainAngleToReference( ...
        summary.sigma_n, summary.sigma_s, referenceSummary.sigma_n, referenceSummary.sigma_s));
end

function summary = emptyLinearSummary(nTime, nBootstraps)
summary = struct( ...
    "u0", zeros(nTime, nBootstraps), ...
    "v0", zeros(nTime, nBootstraps), ...
    "sigma_n", zeros(nTime, nBootstraps), ...
    "sigma_s", zeros(nTime, nBootstraps), ...
    "zeta", zeros(nTime, nBootstraps), ...
    "delta", zeros(nTime, nBootstraps));
end

function summary = emptyCommonSummary(nTime, nBootstraps)
summary = struct( ...
    "uCenter", zeros(nTime, nBootstraps), ...
    "vCenter", zeros(nTime, nBootstraps), ...
    "sigma_n", zeros(nTime, nBootstraps), ...
    "sigma_s", zeros(nTime, nBootstraps), ...
    "zeta", zeros(nTime, nBootstraps));
end

function parameters = modelParametersForIndex(modelIndex)
switch modelIndex
    case 1
        parameters = [ModelParameter.u0v0, ModelParameter.vorticity];
    case 2
        parameters = [ModelParameter.u0v0, ModelParameter.divergence];
    case 3
        parameters = [ModelParameter.u0v0, ModelParameter.strain];
    case 4
        parameters = [ModelParameter.u0v0, ModelParameter.vorticity, ModelParameter.divergence];
    case 5
        parameters = [ModelParameter.u0v0, ModelParameter.strain, ModelParameter.vorticity];
    case 6
        parameters = [ModelParameter.u0v0, ModelParameter.strain, ModelParameter.divergence];
    case 7
        parameters = [ModelParameter.u0v0, ModelParameter.strain, ModelParameter.vorticity, ModelParameter.divergence];
end
end

function diagnostic = stageDiagnosticFromRankedSeries(stageName, stageMode, oldSeries, newSeries, oldScores, newScores)
[~, oldIndex] = max(oldScores);
[~, newIndex] = max(newScores);
diagnostic = emptyStageDiagnostic();
diagnostic.stage = string(stageName);
diagnostic.mode = string(stageMode);
diagnostic.oldIndex = oldIndex;
diagnostic.newIndex = newIndex;

seriesDiagnosticStruct = seriesDiagnostic( ...
    selectSeriesColumn(oldSeries, oldIndex), ...
    selectSeriesColumn(newSeries, newIndex));
diagnostic.uRms = seriesDiagnosticStruct.uRms;
diagnostic.vRms = seriesDiagnosticStruct.vRms;
diagnostic.uvRms = seriesDiagnosticStruct.uvRms;
diagnostic.sigmaNRms = seriesDiagnosticStruct.sigmaNRms;
diagnostic.sigmaSRms = seriesDiagnosticStruct.sigmaSRms;
diagnostic.strainRms = seriesDiagnosticStruct.strainRms;
diagnostic.thetaRms = seriesDiagnosticStruct.thetaRms;
end

function diagnostic = matchedBootstrapDiagnostic(oldSeries, newSeries)
diagnostic = struct( ...
    "uRms", rmsDifference(oldSeries.u, newSeries.u), ...
    "vRms", rmsDifference(oldSeries.v, newSeries.v), ...
    "uvRms", rmsDifference([oldSeries.u(:); oldSeries.v(:)], [newSeries.u(:); newSeries.v(:)]), ...
    "sigmaNRms", rmsDifference(oldSeries.sigma_n, newSeries.sigma_n), ...
    "sigmaSRms", rmsDifference(oldSeries.sigma_s, newSeries.sigma_s), ...
    "strainRms", rmsDifference([oldSeries.sigma_n(:); oldSeries.sigma_s(:)], [newSeries.sigma_n(:); newSeries.sigma_s(:)]), ...
    "thetaRms", rmsDifference(oldSeries.theta, newSeries.theta));
end

function diagnostic = seriesDiagnostic(oldSeries, newSeries)
diagnostic = struct( ...
    "uRms", rmsDifference(oldSeries.u, newSeries.u), ...
    "vRms", rmsDifference(oldSeries.v, newSeries.v), ...
    "uvRms", rmsDifference([oldSeries.u(:); oldSeries.v(:)], [newSeries.u(:); newSeries.v(:)]), ...
    "sigmaNRms", rmsDifference(oldSeries.sigma_n, newSeries.sigma_n), ...
    "sigmaSRms", rmsDifference(oldSeries.sigma_s, newSeries.sigma_s), ...
    "strainRms", rmsDifference([oldSeries.sigma_n(:); oldSeries.sigma_s(:)], [newSeries.sigma_n(:); newSeries.sigma_s(:)]), ...
    "thetaRms", rmsDifference(oldSeries.theta, newSeries.theta));
end

function series = selectSeriesColumn(series, index)
series = struct( ...
    "u", series.u(:, index), ...
    "v", series.v(:, index), ...
    "sigma_n", series.sigma_n(:, index), ...
    "sigma_s", series.sigma_s(:, index), ...
    "theta", series.theta(:, index));
end

function value = rmsDifference(a, b)
a = reshape(a, [], 1);
b = reshape(b, [], 1);
value = sqrt(mean((a - b).^2, "omitnan"));
end

function diagnostic = emptyStageDiagnostic()
diagnostic = struct( ...
    "stage", "", ...
    "mode", "", ...
    "oldIndex", NaN, ...
    "newIndex", NaN, ...
    "uRms", NaN, ...
    "vRms", NaN, ...
    "uvRms", NaN, ...
    "sigmaNRms", NaN, ...
    "sigmaSRms", NaN, ...
    "strainRms", NaN, ...
    "thetaRms", NaN);
end

function displayComparisonSummary(comparison)
fprintf("\nSite 1 Oscroft fair comparison\n");
fprintf("  data: %s\n", comparison.site.dataPath);
fprintf("  shared resamples: %d bootstraps, seed %d\n", ...
    comparison.settings.nBootstraps, comparison.settings.randomSeed);
fprintf("  full-fit common-space RMS: uv=%.6g, strain=%.6g, theta=%.6g deg\n", ...
    comparison.fullFitDiagnostic.uvRms, ...
    comparison.fullFitDiagnostic.strainRms, ...
    comparison.fullFitDiagnostic.thetaRms);
fprintf("  matched shared-bootstrap RMS: uv=%.6g, strain=%.6g, theta=%.6g deg\n", ...
    comparison.matchedSharedBootstrapDiagnostic.uvRms, ...
    comparison.matchedSharedBootstrapDiagnostic.strainRms, ...
    comparison.matchedSharedBootstrapDiagnostic.thetaRms);
disp(struct2table(comparison.stageDiagnostics))
end

function bootstrap = loadOrBuildPublishedGriddedBootstrap(scriptDir, trajectories, options)
arguments
    scriptDir {mustBeTextScalar}
    trajectories {mustBeA(trajectories, "TrajectorySpline"), mustBeVector, mustBeNonempty}
    options.nBootstraps (1,1) double {mustBeInteger, mustBePositive}
    options.randomSeed (1,1) double {mustBeInteger, mustBeFinite}
    options.scoreStride (1,1) double {mustBeInteger, mustBePositive}
    options.psiS (1,3) double {mustBeInteger, mustBeNonnegative}
    options.fastS (1,1) double {mustBeInteger, mustBeNonnegative}
    options.mesoscaleConstraint {mustBeTextScalar, mustBeMember(options.mesoscaleConstraint, ["none", "zeroVorticity", "zeroStrain"])}
end

bootstrapPath = fullfile( ...
    scriptDir, ...
    "..", "GriddedStreamfunction", "Examples", "FluidsPaperCaseStudy", "BootstrapData", ...
    publishedGriddedBootstrapFilename( ...
        1, ...
        nBootstraps=options.nBootstraps, ...
        randomSeed=options.randomSeed, ...
        scoreStride=options.scoreStride, ...
        psiS=options.psiS, ...
        fastS=options.fastS, ...
        mesoscaleConstraint=options.mesoscaleConstraint));

if isfile(bootstrapPath)
    try
        fileData = load(bootstrapPath, "bootstrap");
        if isfield(fileData, "bootstrap") && isa(fileData.bootstrap, "GriddedStreamfunctionBootstrap")
            bootstrap = fileData.bootstrap;
            return
        end
    catch
    end
end

bootstrap = GriddedStreamfunctionBootstrap( ...
    trajectories, ...
    nBootstraps=options.nBootstraps, ...
    randomSeed=options.randomSeed, ...
    scoreStride=options.scoreStride, ...
    psiS=options.psiS, ...
    fastS=options.fastS, ...
    mesoscaleConstraint=options.mesoscaleConstraint);
end

function filename = publishedGriddedBootstrapFilename(siteNumber, options)
arguments
    siteNumber (1,1) double {mustBeMember(siteNumber, [1 2])}
    options.nBootstraps (1,1) double {mustBeInteger, mustBePositive}
    options.randomSeed (1,1) double {mustBeInteger, mustBeFinite}
    options.scoreStride (1,1) double {mustBeInteger, mustBePositive}
    options.psiS (1,3) double {mustBeInteger, mustBeNonnegative}
    options.fastS (1,1) double {mustBeInteger, mustBeNonnegative}
    options.mesoscaleConstraint {mustBeTextScalar, mustBeMember(options.mesoscaleConstraint, ["none", "zeroVorticity", "zeroStrain"])}
end

psiSTag = join(string(options.psiS), "-");
filename = "Rho" + siteNumber + ...
    "GriddedStreamfunctionBootstrapFits" + options.nBootstraps + ...
    "_seed" + options.randomSeed + ...
    "_stride" + options.scoreStride + ...
    "_fastS" + options.fastS + ...
    "_psiS" + psiSTag + ...
    "_mesoscaleConstraint-" + string(options.mesoscaleConstraint) + ".mat";
end
