function filename = site1OscroftFairComparisonCacheFilename(options)
arguments
    options.nBootstraps (1,1) double {mustBeInteger, mustBePositive}
    options.randomSeed (1,1) double {mustBeInteger, mustBeFinite}
    options.scoreStride (1,1) double {mustBeInteger, mustBePositive}
    options.oldDof (1,1) double {mustBeInteger, mustBePositive}
    options.oldModelIndex (1,1) double {mustBeInteger, mustBeMember(options.oldModelIndex, 1:7)}
    options.psiS (1,3) double {mustBeInteger, mustBeNonnegative}
    options.fastS (1,1) double {mustBeInteger, mustBeNonnegative}
    options.mesoscaleConstraint {mustBeTextScalar, mustBeMember(options.mesoscaleConstraint, ["none", "zeroVorticity", "zeroStrain"])}
    options.shouldLoadPublishedBaseline (1,1) logical
end

psiSTag = join(string(options.psiS), "-");
filename = "Rho1OscroftFairComparison" + options.nBootstraps + ...
    "_seed" + options.randomSeed + ...
    "_stride" + options.scoreStride + ...
    "_oldDof" + options.oldDof + ...
    "_oldModel" + options.oldModelIndex + ...
    "_fastS" + options.fastS + ...
    "_psiS" + psiSTag + ...
    "_mesoscaleConstraint-" + string(options.mesoscaleConstraint) + ...
    "_publishedBaseline-" + string(options.shouldLoadPublishedBaseline) + ".mat";
end
