function [summary, scalarSummary] = extractSummaryFromFit(fit, queryTimes)
mx = reshape(fit.centerOfMassTrajectory.x(queryTimes), [], 1);
my = reshape(fit.centerOfMassTrajectory.y(queryTimes), [], 1);

summary = struct( ...
    "uCenter", reshape(fit.uMesoscale(queryTimes, mx, my), [], 1), ...
    "vCenter", reshape(fit.vMesoscale(queryTimes, mx, my), [], 1), ...
    "sigma_n", reshape(fit.sigma_n(queryTimes, mx, my), [], 1), ...
    "sigma_s", reshape(fit.sigma_s(queryTimes, mx, my), [], 1), ...
    "zeta", reshape(fit.zeta(queryTimes, mx, my), [], 1));
scalarSummary = struct( ...
    "kappaEstimate", GriddedStreamfunctionBootstrap.kappaEstimateFromFit(fit));
end
