remote_theme: just-the-docs/just-the-docs
title: Advection-diffusion models
description: Integrate and estimate advection-diffusion models

search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "Advection-diffusion models on GitHub":
    - "https://github.com/JeffreyEarly/advection-diffusion-models"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

color_scheme: light
