classdef IntegratorWithObstaclesKnownIssueTests < matlab.unittest.TestCase

    methods (Test)
        function revealsPeriodicMultiWrapObstacleMiss(testCase)
            obstacle = polyshape([0.5 1.5 1.5 0.5],[0 0 1 1]);

            integrator = IntegratorWithObstacles( ...
                @(~, p) repmat([1 0], size(p,1), 1), ...
                [2 0.5], ...
                9, ...
                0, ...
                [0 -Inf], ...
                [4 Inf], ...
                obstacle, ...
                [1 0]);

            y = integrator.StepForwardOneIncrement;

            % Unwrapped motion should reflect off the obstacle copies at
            % x = 4.5 and x = 1.5, and then off x = 4.5 again, ending at x = 4.
            testCase.verifyEqual(y, [4 0.5], "AbsTol", 2e-3);
            testCase.verifyFalse(isinterior(obstacle, mod(y(1),4), y(2)));
            testCase.verifyEqual(integrator.currentTime, 9);
            testCase.verifyEqual(integrator.totalIterations, 1);
        end

        function revealsReflectionLoopBailout(testCase)
            obstacles = [ ...
                polyshape([0 1 1 0],[0 0 1 1]); ...
                polyshape([2 3 3 2],[0 0 1 1]) ...
                ];

            integrator = IntegratorWithObstacles( ...
                @(~, p) repmat([100 0], size(p,1), 1), ...
                [1.5 0.5], ...
                1, ...
                0, ...
                [-Inf -Inf], ...
                [Inf Inf], ...
                obstacles, ...
                [0 0]);

            lastwarn('');
            y = integrator.StepForwardOneIncrement;
            warningMessage = lastwarn;

            testCase.verifyEmpty(warningMessage);
            testCase.verifyEqual(y, [1.5 0.5], "AbsTol", 2e-3);
            testCase.verifyFalse(isinterior(obstacles(1), y(1), y(2)));
            testCase.verifyFalse(isinterior(obstacles(2), y(1), y(2)));
            testCase.verifyEqual(integrator.currentTime, 1);
            testCase.verifyEqual(integrator.totalIterations, 1);
        end
    end

end
