function sampleData = resampledTrajectorySampleData(observedSampleData, sampledIndices)
sampledIndices = reshape(sampledIndices, [], 1);
nObservedTrajectories = numel(observedSampleData.tCell);
if any(sampledIndices < 1 | sampledIndices > nObservedTrajectories | sampledIndices ~= floor(sampledIndices))
    error("GriddedStreamfunction:InvalidResampledTrajectoryIndices", ...
        "sampledIndices must be positive integer indices into the observed trajectory sample cache.");
end

tCell = observedSampleData.tCell(sampledIndices);
xCell = observedSampleData.xCell(sampledIndices);
yCell = observedSampleData.yCell(sampledIndices);
xDotCell = observedSampleData.xDotCell(sampledIndices);
yDotCell = observedSampleData.yDotCell(sampledIndices);

sampleData = struct( ...
    "tCell", {tCell}, ...
    "xCell", {xCell}, ...
    "yCell", {yCell}, ...
    "xDotCell", {xDotCell}, ...
    "yDotCell", {yDotCell}, ...
    "allT", vertcat(tCell{:}), ...
    "allX", vertcat(xCell{:}), ...
    "allY", vertcat(yCell{:}), ...
    "allXDot", vertcat(xDotCell{:}), ...
    "allYDot", vertcat(yDotCell{:}), ...
    "sampleSupportTimes", unique(vertcat(tCell{:}), "sorted"));
end
