function sampleData = sampleTrajectoryData(trajectories)
nTrajectories = numel(trajectories);
tCell = cell(nTrajectories, 1);
xCell = cell(nTrajectories, 1);
yCell = cell(nTrajectories, 1);
xDotCell = cell(nTrajectories, 1);
yDotCell = cell(nTrajectories, 1);

for iTrajectory = 1:nTrajectories
    ti = reshape(trajectories(iTrajectory).t, [], 1);
    tCell{iTrajectory} = ti;
    xCell{iTrajectory} = reshape(trajectories(iTrajectory).x(ti), [], 1);
    yCell{iTrajectory} = reshape(trajectories(iTrajectory).y(ti), [], 1);
    xDotCell{iTrajectory} = reshape(trajectories(iTrajectory).u(ti), [], 1);
    yDotCell{iTrajectory} = reshape(trajectories(iTrajectory).v(ti), [], 1);
end

sampleData = struct( ...
    "tCell", {tCell}, ...
    "xCell", {xCell}, ...
    "yCell", {yCell}, ...
    "xDotCell", {xDotCell}, ...
    "yDotCell", {yDotCell}, ...
    "allT", vertcat(tCell{:}), ...
    "allX", vertcat(xCell{:}), ...
    "allY", vertcat(yCell{:}), ...
    "allXDot", vertcat(xDotCell{:}), ...
    "allYDot", vertcat(yDotCell{:}), ...
    "sampleSupportTimes", unique(vertcat(tCell{:}), "sorted"));
end
