classdef OscroftFairComparisonUnitTests < matlab.unittest.TestCase

    methods (TestClassSetup)
        function addComparisonFolderToPath(testCase)
            comparisonDir = fileparts(fileparts(mfilename("fullpath")));
            addpath(comparisonDir);
            testCase.addTeardown(@() rmpath(comparisonDir));
        end
    end

    methods (Test)
        function sharedBootstrapComparisonAgreesForZeroVorticityLinearField(testCase)
            [t, x, y, trajectories] = OscroftFairComparisonUnitTests.zeroVorticityLinearFieldData();
            bootstrapIndices = OscroftFairComparisonUnitTests.deterministicBootstrapIndices(size(x, 2), 6, 13);
            scoreIndices = 1:2:numel(t);

            oldEnsemble = OscroftFairComparisonUnitTests.linearCommonSpaceEnsemble(x, y, t, bootstrapIndices);
            newEnsemble = OscroftFairComparisonUnitTests.griddedCommonSpaceEnsemble(trajectories, t, bootstrapIndices);

            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.fullSummary.uCenter - newEnsemble.fullSummary.uCenter), [], "all"), 5e-3)
            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.fullSummary.vCenter - newEnsemble.fullSummary.vCenter), [], "all"), 5e-3)
            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.fullSummary.sigma_n - newEnsemble.fullSummary.sigma_n), [], "all"), 2e-11)
            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.fullSummary.sigma_s - newEnsemble.fullSummary.sigma_s), [], "all"), 2e-11)

            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.summary.uCenter - newEnsemble.summary.uCenter), [], "all"), 8e-3)
            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.summary.vCenter - newEnsemble.summary.vCenter), [], "all"), 8e-3)
            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.summary.sigma_n - newEnsemble.summary.sigma_n), [], "all"), 2e-11)
            testCase.verifyLessThanOrEqual(max(abs(oldEnsemble.summary.sigma_s - newEnsemble.summary.sigma_s), [], "all"), 2e-11)

            referenceScores = computeComparisonConsensusScores(oldEnsemble.summary, scoreIndices, "zeroVorticity");
            copiedScores = computeComparisonConsensusScores(struct( ...
                "uCenter", oldEnsemble.summary.uCenter, ...
                "vCenter", oldEnsemble.summary.vCenter, ...
                "sigma_n", oldEnsemble.summary.sigma_n, ...
                "sigma_s", oldEnsemble.summary.sigma_s, ...
                "zeta", oldEnsemble.summary.zeta), scoreIndices, "zeroVorticity");
            testCase.verifyEqual(referenceScores.joint, copiedScores.joint, "AbsTol", 1e-12)
        end

        function thetaBranchAlignmentCollapsesEquivalentNinetyDegreeBranches(testCase)
            thetaReference = deg2rad((10:5:30)');
            thetaBootstrap = [thetaReference, thetaReference + pi/2, thetaReference - pi/2];
            sigma_n = cos(2 * thetaBootstrap);
            sigma_s = sin(2 * thetaBootstrap);

            rawTheta = atan2(sigma_s, sigma_n) * 90/pi;
            alignedTheta = alignPrincipalStrainAngleToReference( ...
                sigma_n, sigma_s, cos(2 * thetaReference), sin(2 * thetaReference), units="degrees");

            rawWidth = max(rawTheta, [], 2) - min(rawTheta, [], 2);
            alignedWidth = max(alignedTheta, [], 2) - min(alignedTheta, [], 2);

            testCase.verifyGreaterThan(max(rawWidth), 80)
            testCase.verifyLessThanOrEqual(max(alignedWidth), 1e-10)
        end

        function strainKdeComparisonResolvesRequestedDays(testCase)
            comparison = OscroftFairComparisonUnitTests.syntheticStrainKdeComparison();
            kdeComparison = buildSite1BootstrapStrainKdeComparison(comparison, [0.15 1.9 3.2]);

            testCase.verifyEqual(kdeComparison.timeIndices, [1; 3; 4])
            testCase.verifyEqual(kdeComparison.matchedTimeDays, [0; 2; 3], "AbsTol", 1e-12)

            testCase.verifyError( ...
                @() buildSite1BootstrapStrainKdeComparison(comparison, [-0.1 1.0]), ...
                "GriddedStreamfunction:ComparisonTimeOutOfRange")
            testCase.verifyError( ...
                @() buildSite1BootstrapStrainKdeComparison(comparison, [0.1 0.2]), ...
                "GriddedStreamfunction:DuplicateComparisonTimeIndex")
        end

        function strainKdeComparisonBuildsFiniteSharedPanels(testCase)
            comparison = OscroftFairComparisonUnitTests.syntheticStrainKdeComparison();
            kdeComparison = buildSite1BootstrapStrainKdeComparison(comparison, [0 2 4]);

            testCase.verifyEqual(size(kdeComparison.panels), [3 2])
            testCase.verifyGreaterThan(kdeComparison.bounds.halfWidth, 0)

            for iPanel = 1:numel(kdeComparison.panels)
                panel = kdeComparison.panels(iPanel);
                testCase.verifyTrue(all(isfinite(panel.samples), "all"))
                testCase.verifyTrue(all(isfinite(panel.fullPoint), "all"))
                testCase.verifyTrue(all(isfinite(panel.density), "all"))
                testCase.verifyTrue(all(isfinite(panel.contourLevels)))
                testCase.verifyEqual(panel.gridVectors{1}(1), kdeComparison.bounds.minimum(1), "AbsTol", 1e-12)
                testCase.verifyEqual(panel.gridVectors{1}(end), kdeComparison.bounds.maximum(1), "AbsTol", 1e-12)
                testCase.verifyEqual(panel.gridVectors{2}(1), kdeComparison.bounds.minimum(2), "AbsTol", 1e-12)
                testCase.verifyEqual(panel.gridVectors{2}(end), kdeComparison.bounds.maximum(2), "AbsTol", 1e-12)
            end
        end

        function site1FairComparisonCacheFilenameEncodesFullIdentity(testCase)
            filenameDefault = site1OscroftFairComparisonCacheFilename( ...
                nBootstraps=1000, ...
                randomSeed=0, ...
                scoreStride=6, ...
                oldDof=4, ...
                oldModelIndex=3, ...
                psiS=[2 2 3], ...
                fastS=3, ...
                mesoscaleConstraint="zeroVorticity", ...
                shouldLoadPublishedBaseline=false);

            testCase.verifyEqual( ...
                filenameDefault, ...
                "Rho1OscroftFairComparison1000_seed0_stride6_oldDof4_oldModel3_fastS3_psiS2-2-3_mesoscaleConstraint-zeroVorticity_publishedBaseline-false.mat")

            testCase.verifyNotEqual(filenameDefault, site1OscroftFairComparisonCacheFilename( ...
                nBootstraps=500, ...
                randomSeed=0, ...
                scoreStride=6, ...
                oldDof=4, ...
                oldModelIndex=3, ...
                psiS=[2 2 3], ...
                fastS=3, ...
                mesoscaleConstraint="zeroVorticity", ...
                shouldLoadPublishedBaseline=false))

            testCase.verifyNotEqual(filenameDefault, site1OscroftFairComparisonCacheFilename( ...
                nBootstraps=1000, ...
                randomSeed=1, ...
                scoreStride=6, ...
                oldDof=4, ...
                oldModelIndex=3, ...
                psiS=[2 2 3], ...
                fastS=3, ...
                mesoscaleConstraint="zeroVorticity", ...
                shouldLoadPublishedBaseline=false))

            testCase.verifyNotEqual(filenameDefault, site1OscroftFairComparisonCacheFilename( ...
                nBootstraps=1000, ...
                randomSeed=0, ...
                scoreStride=6, ...
                oldDof=4, ...
                oldModelIndex=3, ...
                psiS=[2 2 3], ...
                fastS=3, ...
                mesoscaleConstraint="zeroVorticity", ...
                shouldLoadPublishedBaseline=true))
        end

        function site1SmokeTestRunsAndStaysInSmallDifferenceRegime(testCase)
            helperPath = which("buildSite1OscroftFairComparison");
            dataPath = fullfile(fileparts(helperPath), "..", "ExampleData", "LatMix2011", "smoothedGriddedRho1Drifters.mat");
            if ~isfile(dataPath)
                testCase.assumeFail(sprintf("Missing local example data at %s.", dataPath))
            end

            comparison = buildSite1OscroftFairComparison( ...
                nBootstraps=6, ...
                randomSeed=5, ...
                shouldLoadPublishedBaseline=false, ...
                shouldUseCache=false, ...
                displaySummary=false);

            testCase.verifyEqual(numel(comparison.stageDiagnostics), 2)
            testCase.verifyTrue(all(isfinite(comparison.old.shared.commonSummary.uCenter), "all"))
            testCase.verifyTrue(all(isfinite(comparison.old.shared.commonSummary.vCenter), "all"))
            testCase.verifyTrue(all(isfinite(comparison.new.shared.summary.uCenter), "all"))
            testCase.verifyTrue(all(isfinite(comparison.new.shared.summary.vCenter), "all"))
            testCase.verifyLessThanOrEqual(comparison.fullFitDiagnostic.uvRms, 5e-3)
            testCase.verifyLessThanOrEqual(comparison.fullFitDiagnostic.strainRms, 3e-6)
            testCase.verifyLessThanOrEqual(comparison.matchedSharedBootstrapDiagnostic.uvRms, 1.5e-2)
            testCase.verifyLessThanOrEqual(comparison.matchedSharedBootstrapDiagnostic.strainRms, 3e-6)
        end

        function site1FairComparisonCacheCanBeReused(testCase)
            helperPath = which("buildSite1OscroftFairComparison");
            dataPath = fullfile(fileparts(helperPath), "..", "ExampleData", "LatMix2011", "smoothedGriddedRho1Drifters.mat");
            if ~isfile(dataPath)
                testCase.assumeFail(sprintf("Missing local example data at %s.", dataPath))
            end

            cacheDirectory = tempname;
            mkdir(cacheDirectory);
            testCase.addTeardown(@() rmdir(cacheDirectory, "s"));

            comparisonBuilt = buildSite1OscroftFairComparison( ...
                nBootstraps=4, ...
                randomSeed=9, ...
                shouldLoadPublishedBaseline=false, ...
                shouldRefreshCache=true, ...
                cacheDirectory=cacheDirectory, ...
                displaySummary=false);

            cachePath = fullfile(cacheDirectory, site1OscroftFairComparisonCacheFilename( ...
                nBootstraps=4, ...
                randomSeed=9, ...
                scoreStride=6, ...
                oldDof=4, ...
                oldModelIndex=3, ...
                psiS=[2 2 3], ...
                fastS=3, ...
                mesoscaleConstraint="zeroVorticity", ...
                shouldLoadPublishedBaseline=false));
            testCase.verifyTrue(isfile(cachePath))
            testCase.verifyFalse(comparisonBuilt.cacheInfo.wasLoadedFromCache)

            comparisonCached = buildSite1OscroftFairComparison( ...
                nBootstraps=4, ...
                randomSeed=9, ...
                shouldLoadPublishedBaseline=false, ...
                cacheDirectory=cacheDirectory, ...
                displaySummary=false);

            testCase.verifyTrue(comparisonCached.cacheInfo.wasLoadedFromCache)
            testCase.verifyEqual(comparisonCached.settings, comparisonBuilt.settings)
            testCase.verifyEqual(comparisonCached.old.shared.commonSummary.uCenter, comparisonBuilt.old.shared.commonSummary.uCenter, "AbsTol", 1e-12)
            testCase.verifyEqual(comparisonCached.new.shared.summary.uCenter, comparisonBuilt.new.shared.summary.uCenter, "AbsTol", 1e-12)
        end

        function site1StrainKdeSmokeTestRunsWithDefaultDays(testCase)
            helperPath = which("buildSite1OscroftFairComparison");
            dataPath = fullfile(fileparts(helperPath), "..", "ExampleData", "LatMix2011", "smoothedGriddedRho1Drifters.mat");
            if ~isfile(dataPath)
                testCase.assumeFail(sprintf("Missing local example data at %s.", dataPath))
            end

            kdeComparison = buildSite1BootstrapStrainKdeComparison( ...
                buildSite1OscroftFairComparison( ...
                    nBootstraps=6, ...
                    randomSeed=7, ...
                    shouldLoadPublishedBaseline=false, ...
                    shouldUseCache=false, ...
                    displaySummary=false), ...
                [0.5 2.5 5.0]);

            testCase.verifyEqual(size(kdeComparison.panels), [3 2])
            testCase.verifyEqual(kdeComparison.methodLabels, ["Oscroft"; "Gridded Streamfunction"])
            testCase.verifyTrue(all(isfinite(kdeComparison.matchedTimeDays)))
            testCase.verifyTrue(all(kdeComparison.matchedTimeDays >= 0))
            testCase.verifyGreaterThan(kdeComparison.bounds.halfWidth, 0)
            testCase.verifyTrue(all(arrayfun(@(panel) all(isfinite(panel.samples), "all"), kdeComparison.panels), "all"))
            testCase.verifyTrue(all(arrayfun(@(panel) all(isfinite(panel.fullPoint), "all"), kdeComparison.panels), "all"))
        end
    end

    methods (Static)
        function [t, x, y, trajectories] = zeroVorticityLinearFieldData()
            model = LinearVelocityField(sigma=4.0e-6, theta=pi/9, zeta=0, u0=0.08, v0=-0.05);
            integrator = AdvectionDiffusionIntegrator(model, 0);
            [x0, y0] = ndgrid([-600 0 600] + 1200, [-400 0 400] - 800);
            [t, x, y] = integrator.particleTrajectories(x0(:), y0(:), 12*3600, 900);
            trajectories = GriddedStreamfunctionBootstrapUnitTests.trajectorySplinesFromMatrices(t, x, y);
        end

        function bootstrapIndices = deterministicBootstrapIndices(nDrifters, nBootstraps, randomSeed)
            originalRng = rng;
            cleanupRng = onCleanup(@() rng(originalRng));
            rng(randomSeed);
            bootstrapIndices = randi(nDrifters, nBootstraps, nDrifters);
        end

        function ensemble = linearCommonSpaceEnsemble(x, y, t, bootstrapIndices)
            parametersToEstimate = [ModelParameter.u0v0, ModelParameter.strain];
            [fullParameters, ~] = EstimateLinearVelocityFieldParameters(x, y, t, parametersToEstimate, 4);
            fullSummary = OscroftFairComparisonUnitTests.linearCommonSummary(fullParameters, mean(x, 2), mean(y, 2));

            nTime = numel(t);
            nBootstraps = size(bootstrapIndices, 1);
            summary = struct( ...
                "uCenter", zeros(nTime, nBootstraps), ...
                "vCenter", zeros(nTime, nBootstraps), ...
                "sigma_n", zeros(nTime, nBootstraps), ...
                "sigma_s", zeros(nTime, nBootstraps), ...
                "zeta", zeros(nTime, nBootstraps));

            for iBootstrap = 1:nBootstraps
                sampledIndices = bootstrapIndices(iBootstrap, :);
                xSub = x(:, sampledIndices);
                ySub = y(:, sampledIndices);
                parameters = EstimateLinearVelocityFieldParameters(xSub, ySub, t, parametersToEstimate, 4);
                bootstrapSummary = OscroftFairComparisonUnitTests.linearCommonSummary( ...
                    parameters, mean(xSub, 2), mean(ySub, 2));
                summary.uCenter(:, iBootstrap) = bootstrapSummary.uCenter;
                summary.vCenter(:, iBootstrap) = bootstrapSummary.vCenter;
                summary.sigma_n(:, iBootstrap) = bootstrapSummary.sigma_n;
                summary.sigma_s(:, iBootstrap) = bootstrapSummary.sigma_s;
                summary.zeta(:, iBootstrap) = bootstrapSummary.zeta;
            end

            ensemble = struct("fullSummary", fullSummary, "summary", summary);
        end

        function ensemble = griddedCommonSpaceEnsemble(trajectories, queryTimes, bootstrapIndices)
            fitOptions = struct( ...
                "psiS", [2 2 3], ...
                "fastS", 3, ...
                "mesoscaleConstraint", "zeroVorticity", ...
                "buildDecomposition", false);
            fitArguments = namedargs2cell(fitOptions);

            fullFit = GriddedStreamfunction.fromTrajectories(trajectories, fitArguments{:});
            fullSummary = OscroftFairComparisonUnitTests.griddedSummaryFromFit(fullFit, queryTimes);

            nTime = numel(queryTimes);
            nBootstraps = size(bootstrapIndices, 1);
            summary = struct( ...
                "uCenter", zeros(nTime, nBootstraps), ...
                "vCenter", zeros(nTime, nBootstraps), ...
                "sigma_n", zeros(nTime, nBootstraps), ...
                "sigma_s", zeros(nTime, nBootstraps), ...
                "zeta", zeros(nTime, nBootstraps));

            for iBootstrap = 1:nBootstraps
                sampledTrajectories = reshape(trajectories(bootstrapIndices(iBootstrap, :)), [], 1);
                fit = GriddedStreamfunction.fromTrajectories(sampledTrajectories, fitArguments{:});
                bootstrapSummary = OscroftFairComparisonUnitTests.griddedSummaryFromFit(fit, queryTimes);
                summary.uCenter(:, iBootstrap) = bootstrapSummary.uCenter;
                summary.vCenter(:, iBootstrap) = bootstrapSummary.vCenter;
                summary.sigma_n(:, iBootstrap) = bootstrapSummary.sigma_n;
                summary.sigma_s(:, iBootstrap) = bootstrapSummary.sigma_s;
                summary.zeta(:, iBootstrap) = bootstrapSummary.zeta;
            end

            ensemble = struct("fullSummary", fullSummary, "summary", summary);
        end

        function summary = griddedSummaryFromFit(fit, queryTimes)
            mx = reshape(fit.centerOfMassTrajectory.x(queryTimes), [], 1);
            my = reshape(fit.centerOfMassTrajectory.y(queryTimes), [], 1);
            summary = struct( ...
                "uCenter", reshape(fit.uMesoscale(queryTimes, mx, my), [], 1), ...
                "vCenter", reshape(fit.vMesoscale(queryTimes, mx, my), [], 1), ...
                "sigma_n", reshape(fit.sigma_n(queryTimes, mx, my), [], 1), ...
                "sigma_s", reshape(fit.sigma_s(queryTimes, mx, my), [], 1), ...
                "zeta", reshape(fit.zeta(queryTimes, mx, my), [], 1));
        end

        function summary = linearCommonSummary(parameters, mx, my)
            u0 = reshape(parameters.u0, [], 1);
            v0 = reshape(parameters.v0, [], 1);
            sigma_n = reshape(parameters.sigma_n, [], 1);
            sigma_s = reshape(parameters.sigma_s, [], 1);
            zeta = reshape(parameters.zeta, [], 1);
            delta = reshape(parameters.delta, [], 1);
            mx = reshape(mx, [], 1);
            my = reshape(my, [], 1);

            summary = struct( ...
                "uCenter", u0 + 0.5 * (sigma_n + delta) .* mx + 0.5 * (sigma_s - zeta) .* my, ...
                "vCenter", v0 + 0.5 * (sigma_s + zeta) .* mx + 0.5 * (delta - sigma_n) .* my, ...
                "sigma_n", sigma_n, ...
                "sigma_s", sigma_s, ...
                "zeta", zeta);
        end

        function comparison = syntheticStrainKdeComparison()
            queryTimes = (0:4)' * 86400;
            nTime = numel(queryTimes);
            nBootstraps = 6;
            [timeGrid, bootstrapGrid] = ndgrid(1:nTime, 1:nBootstraps);

            oldSigmaN = 1e-6 * (0.4 * timeGrid + 0.25 * cos(bootstrapGrid));
            oldSigmaS = 1e-6 * (-0.2 * timeGrid + 0.35 * sin(bootstrapGrid));
            newSigmaN = oldSigmaN + 0.15e-6;
            newSigmaS = oldSigmaS - 0.10e-6;

            comparison = struct( ...
                "site", struct("queryTimes", queryTimes), ...
                "old", struct("shared", struct( ...
                    "commonSummary", struct("sigma_n", oldSigmaN, "sigma_s", oldSigmaS), ...
                    "fullCommonSummary", struct( ...
                        "sigma_n", mean(oldSigmaN, 2), ...
                        "sigma_s", mean(oldSigmaS, 2)))), ...
                "new", struct("shared", struct( ...
                    "commonSummary", struct("sigma_n", newSigmaN, "sigma_s", newSigmaS), ...
                    "fullCommonSummary", struct( ...
                        "sigma_n", mean(newSigmaN, 2), ...
                        "sigma_s", mean(newSigmaS, 2)))));
        end
    end
end
