function diagnostics = griddedStreamfunctionEffectiveDiagnostics(fit, t, x, y)
arguments
    fit (1,1) GriddedStreamfunction
    t (:,1) double {mustBeReal, mustBeFinite}
    x (:,:) double {mustBeReal, mustBeFinite}
    y (:,:) double {mustBeReal, mustBeFinite}
end

if ~isequal(size(x), size(y))
    error("GriddedStreamfunction:ExampleCoordinateSizeMismatch", ...
        "x and y must have the same size.");
end
if size(x, 1) ~= numel(t)
    error("GriddedStreamfunction:ExampleTimeSizeMismatch", ...
        "The first dimension of x and y must match numel(t).");
end

nTimes = numel(t);
nDrifters = size(x, 2);
expectedSampleCount = nTimes * nDrifters;
if numel(fit.observedXVelocity) ~= expectedSampleCount
    error("GriddedStreamfunction:ExampleSampleCountMismatch", ...
        "Expected %d synchronous velocity samples in the estimator, but found %d.", ...
        expectedSampleCount, numel(fit.observedXVelocity));
end

mxObserved = mean(x, 2);
myObserved = mean(y, 2);
mxFit = fit.centerOfMassTrajectory.x(t);
myFit = fit.centerOfMassTrajectory.y(t);
mxFitGrid = repmat(mxFit, 1, nDrifters);
myFitGrid = repmat(myFit, 1, nDrifters);

uObserved = reshape(fit.observedXVelocity, nTimes, nDrifters);
vObserved = reshape(fit.observedYVelocity, nTimes, nDrifters);
uMesoscale = reshape(fit.uMesoscaleObserved, nTimes, nDrifters);
vMesoscale = reshape(fit.vMesoscaleObserved, nTimes, nDrifters);
uBackgroundObserved = reshape(fit.uBackgroundObserved, nTimes, nDrifters);
vBackgroundObserved = reshape(fit.vBackgroundObserved, nTimes, nDrifters);
uSubmesoscale = reshape(fit.uSubmesoscaleObserved, nTimes, nDrifters);
vSubmesoscale = reshape(fit.vSubmesoscaleObserved, nTimes, nDrifters);

xBackground = zeros(nTimes, nDrifters);
yBackground = zeros(nTimes, nDrifters);
xMesoscale = zeros(nTimes, nDrifters);
yMesoscale = zeros(nTimes, nDrifters);
xSubmesoscale = zeros(nTimes, nDrifters);
ySubmesoscale = zeros(nTimes, nDrifters);
qMesoscale = zeros(nTimes, nDrifters);
rMesoscale = zeros(nTimes, nDrifters);
qSubmesoscale = zeros(nTimes, nDrifters);
rSubmesoscale = zeros(nTimes, nDrifters);
for iDrifter = 1:nDrifters
    xBackground(:, iDrifter) = fit.backgroundTrajectories(iDrifter).x(t);
    yBackground(:, iDrifter) = fit.backgroundTrajectories(iDrifter).y(t);
    xMesoscale(:, iDrifter) = fit.mesoscaleTrajectories(iDrifter).x(t);
    yMesoscale(:, iDrifter) = fit.mesoscaleTrajectories(iDrifter).y(t);
    xSubmesoscale(:, iDrifter) = fit.submesoscaleTrajectories(iDrifter).x(t);
    ySubmesoscale(:, iDrifter) = fit.submesoscaleTrajectories(iDrifter).y(t);
    qMesoscale(:, iDrifter) = fit.centeredMesoscaleTrajectories(iDrifter).x(t);
    rMesoscale(:, iDrifter) = fit.centeredMesoscaleTrajectories(iDrifter).y(t);
    qSubmesoscale(:, iDrifter) = fit.centeredSubmesoscaleTrajectories(iDrifter).x(t);
    rSubmesoscale(:, iDrifter) = fit.centeredSubmesoscaleTrajectories(iDrifter).y(t);
end

raw = struct( ...
    "uObserved", uObserved, ...
    "vObserved", vObserved, ...
    "uMesoscale", uMesoscale, ...
    "vMesoscale", vMesoscale, ...
    "uBackground", fit.uBackground(t), ...
    "vBackground", fit.vBackground(t), ...
    "uBackgroundObserved", uBackgroundObserved, ...
    "vBackgroundObserved", vBackgroundObserved, ...
    "uSubmesoscale", uSubmesoscale, ...
    "vSubmesoscale", vSubmesoscale, ...
    "qObserved", x - mxFitGrid, ...
    "rObserved", y - myFitGrid, ...
    "xMesoscale", xMesoscale, ...
    "yMesoscale", yMesoscale, ...
    "xBackground", xBackground, ...
    "yBackground", yBackground, ...
    "xSubmesoscale", xSubmesoscale, ...
    "ySubmesoscale", ySubmesoscale, ...
    "qMesoscale", qMesoscale, ...
    "rMesoscale", rMesoscale, ...
    "qSubmesoscale", qSubmesoscale, ...
    "rSubmesoscale", rSubmesoscale, ...
    "observedSpeedRms", sqrt(mean(uObserved.^2 + vObserved.^2, 2)), ...
    "mesoscaleSpeedRms", sqrt(mean(uMesoscale.^2 + vMesoscale.^2, 2)), ...
    "backgroundSpeedRms", sqrt(fit.uBackground(t).^2 + fit.vBackground(t).^2), ...
    "submesoscaleSpeedRms", sqrt(mean(uSubmesoscale.^2 + vSubmesoscale.^2, 2)));

diagnostics = struct( ...
    "mxObserved", mxObserved, ...
    "myObserved", myObserved, ...
    "mxFit", mxFit, ...
    "myFit", myFit, ...
    "raw", raw, ...
    "effective", raw);
end
