function diagnostics = griddedStreamfunctionEffectiveDiagnostics(fit, t, x, y)
arguments
    fit (1,1) GriddedStreamfunction
    t (:,1) double {mustBeReal, mustBeFinite}
    x (:,:) double {mustBeReal, mustBeFinite}
    y (:,:) double {mustBeReal, mustBeFinite}
end

if ~isequal(size(x), size(y))
    error("GriddedStreamfunction:ExampleCoordinateSizeMismatch", ...
        "x and y must have the same size.");
end
if size(x, 1) ~= numel(t)
    error("GriddedStreamfunction:ExampleTimeSizeMismatch", ...
        "The first dimension of x and y must match numel(t).");
end

nTimes = numel(t);
nDrifters = size(x, 2);
expectedSampleCount = nTimes * nDrifters;
if numel(fit.observedXVelocity) ~= expectedSampleCount
    error("GriddedStreamfunction:ExampleSampleCountMismatch", ...
        "Expected %d synchronous velocity samples in the estimator, but found %d.", ...
        expectedSampleCount, numel(fit.observedXVelocity));
end

mxObserved = mean(x, 2);
myObserved = mean(y, 2);
mxFit = fit.centerOfMassTrajectory.x(t);
myFit = fit.centerOfMassTrajectory.y(t);
mxFitGrid = repmat(mxFit, 1, nDrifters);
myFitGrid = repmat(myFit, 1, nDrifters);
mxObservedGrid = repmat(mxObserved, 1, nDrifters);
myObservedGrid = repmat(myObserved, 1, nDrifters);

uObserved = reshape(fit.observedXVelocity, nTimes, nDrifters);
vObserved = reshape(fit.observedYVelocity, nTimes, nDrifters);
uMesoscaleRaw = reshape(fit.uMesoscaleObserved, nTimes, nDrifters);
vMesoscaleRaw = reshape(fit.vMesoscaleObserved, nTimes, nDrifters);
uBackgroundRawObserved = reshape(fit.uBackgroundObserved, nTimes, nDrifters);
vBackgroundRawObserved = reshape(fit.vBackgroundObserved, nTimes, nDrifters);
uSubmesoscale = reshape(fit.submesoscaleX, nTimes, nDrifters);
vSubmesoscale = reshape(fit.submesoscaleY, nTimes, nDrifters);

uBackgroundRaw = fit.uBackground(t);
vBackgroundRaw = fit.vBackground(t);
uMesoscaleMean = mean(uMesoscaleRaw, 2);
vMesoscaleMean = mean(vMesoscaleRaw, 2);
uMesoscaleEffective = uMesoscaleRaw - uMesoscaleMean;
vMesoscaleEffective = vMesoscaleRaw - vMesoscaleMean;
uBackgroundEffective = uBackgroundRaw + uMesoscaleMean;
vBackgroundEffective = vBackgroundRaw + vMesoscaleMean;
uBackgroundEffectiveObserved = uBackgroundRawObserved + uMesoscaleMean;
vBackgroundEffectiveObserved = vBackgroundRawObserved + vMesoscaleMean;

qObservedFit = x - mxFitGrid;
rObservedFit = y - myFitGrid;
qObservedEffective = x - mxObservedGrid;
rObservedEffective = y - myObservedGrid;

rawQMesoscale = qObservedFit(1, :) + cumtrapz(t, uMesoscaleEffective);
rawRMesoscale = rObservedFit(1, :) + cumtrapz(t, vMesoscaleEffective);
effectiveQMesoscale = qObservedEffective(1, :) + cumtrapz(t, uMesoscaleEffective);
effectiveRMesoscale = rObservedEffective(1, :) + cumtrapz(t, vMesoscaleEffective);

raw = struct( ...
    "uObserved", uObserved, ...
    "vObserved", vObserved, ...
    "uMesoscale", uMesoscaleRaw, ...
    "vMesoscale", vMesoscaleRaw, ...
    "uBackground", uBackgroundRaw, ...
    "vBackground", vBackgroundRaw, ...
    "uBackgroundObserved", uBackgroundRawObserved, ...
    "vBackgroundObserved", vBackgroundRawObserved, ...
    "uSubmesoscale", uSubmesoscale, ...
    "vSubmesoscale", vSubmesoscale, ...
    "qObserved", qObservedFit, ...
    "rObserved", rObservedFit, ...
    "xMesoscale", x(1, :) + cumtrapz(t, uMesoscaleRaw), ...
    "yMesoscale", y(1, :) + cumtrapz(t, vMesoscaleRaw), ...
    "xBackground", cumtrapz(t, uBackgroundRaw), ...
    "yBackground", cumtrapz(t, vBackgroundRaw), ...
    "xSubmesoscale", cumtrapz(t, uSubmesoscale), ...
    "ySubmesoscale", cumtrapz(t, vSubmesoscale), ...
    "qMesoscale", rawQMesoscale, ...
    "rMesoscale", rawRMesoscale, ...
    "observedSpeedRms", sqrt(mean(uObserved.^2 + vObserved.^2, 2)), ...
    "mesoscaleSpeedRms", sqrt(mean(uMesoscaleRaw.^2 + vMesoscaleRaw.^2, 2)), ...
    "backgroundSpeedRms", sqrt(uBackgroundRaw.^2 + vBackgroundRaw.^2), ...
    "submesoscaleSpeedRms", sqrt(mean(uSubmesoscale.^2 + vSubmesoscale.^2, 2)));

effective = struct( ...
    "uObserved", uObserved, ...
    "vObserved", vObserved, ...
    "uMesoscale", uMesoscaleEffective, ...
    "vMesoscale", vMesoscaleEffective, ...
    "uMesoscaleMean", uMesoscaleMean, ...
    "vMesoscaleMean", vMesoscaleMean, ...
    "uBackground", uBackgroundEffective, ...
    "vBackground", vBackgroundEffective, ...
    "uBackgroundObserved", uBackgroundEffectiveObserved, ...
    "vBackgroundObserved", vBackgroundEffectiveObserved, ...
    "uSubmesoscale", uSubmesoscale, ...
    "vSubmesoscale", vSubmesoscale, ...
    "qObserved", qObservedEffective, ...
    "rObserved", rObservedEffective, ...
    "xMesoscale", x(1, :) + cumtrapz(t, uMesoscaleEffective), ...
    "yMesoscale", y(1, :) + cumtrapz(t, vMesoscaleEffective), ...
    "xBackground", cumtrapz(t, uBackgroundEffective), ...
    "yBackground", cumtrapz(t, vBackgroundEffective), ...
    "xSubmesoscale", cumtrapz(t, uSubmesoscale), ...
    "ySubmesoscale", cumtrapz(t, vSubmesoscale), ...
    "qMesoscale", effectiveQMesoscale, ...
    "rMesoscale", effectiveRMesoscale, ...
    "observedSpeedRms", sqrt(mean(uObserved.^2 + vObserved.^2, 2)), ...
    "mesoscaleSpeedRms", sqrt(mean(uMesoscaleEffective.^2 + vMesoscaleEffective.^2, 2)), ...
    "backgroundSpeedRms", sqrt(uBackgroundEffective.^2 + vBackgroundEffective.^2), ...
    "submesoscaleSpeedRms", sqrt(mean(uSubmesoscale.^2 + vSubmesoscale.^2, 2)));

diagnostics = struct( ...
    "mxObserved", mxObserved, ...
    "myObserved", myObserved, ...
    "mxFit", mxFit, ...
    "myFit", myFit, ...
    "raw", raw, ...
    "effective", effective);
end
