function siteFit = loadGriddedStreamfunctionSiteFit(siteNumber)
arguments
    siteNumber (1,1) double {mustBeInteger, mustBeMember(siteNumber, [1 2])}
end

scriptDir = fileparts(mfilename('fullpath'));
dataDir = fullfile(scriptDir, '..', '..', '..', 'ExampleData', 'LatMix2011');
dataPath = fullfile(dataDir, sprintf('smoothedGriddedRho%dDrifters.mat', siteNumber));
if ~isfile(dataPath)
    error('GriddedStreamfunction:MissingExampleData', ...
        'Expected local example data at %s.', dataPath);
end

siteData = load(dataPath);
t = reshape(siteData.t, [], 1);
x = siteData.x(:, 1:(end-1));
y = siteData.y(:, 1:(end-1));
nTimes = numel(t);
nDrifters = size(x, 2);

trajectories = TrajectorySpline.empty(0, 1);
for iDrifter = 1:nDrifters
    trajectories(end+1, 1) = TrajectorySpline(t, x(:, iDrifter), y(:, iDrifter), S=3); %#ok<AGROW>
end

fit = GriddedStreamfunction.fitFromTrajectorySplines(trajectories);

mx = fit.centerOfMassTrajectory.x(t);
my = fit.centerOfMassTrajectory.y(t);
mxGrid = repmat(mx, 1, nDrifters);
myGrid = repmat(my, 1, nDrifters);

sigmaN = fit.sigma_n(t, mx, my);
sigmaS = fit.sigma_s(t, mx, my);
zeta = fit.zeta(t, mx, my);
sigma = sqrt(sigmaN .* sigmaN + sigmaS .* sigmaS);
twoTheta = unwrap(atan2(sigmaS, sigmaN));
thetaDegrees = 180/pi * (twoTheta / 2);

uObserved = reshape(fit.fitState.observedXVelocity, nTimes, nDrifters);
vObserved = reshape(fit.fitState.observedYVelocity, nTimes, nDrifters);
uMesoscale = reshape(fit.fitState.uMesoscaleObserved, nTimes, nDrifters);
vMesoscale = reshape(fit.fitState.vMesoscaleObserved, nTimes, nDrifters);
uBackgroundObserved = reshape(fit.fitState.uBackgroundObserved, nTimes, nDrifters);
vBackgroundObserved = reshape(fit.fitState.vBackgroundObserved, nTimes, nDrifters);
uSubmesoscale = reshape(fit.fitState.submesoscaleX, nTimes, nDrifters);
vSubmesoscale = reshape(fit.fitState.submesoscaleY, nTimes, nDrifters);

uMesoscaleCentered = uMesoscale - mean(uMesoscale, 2);
vMesoscaleCentered = vMesoscale - mean(vMesoscale, 2);
qObserved = x - mxGrid;
rObserved = y - myGrid;
qMesoscale = qObserved(1, :) + cumtrapz(t, uMesoscaleCentered);
rMesoscale = rObserved(1, :) + cumtrapz(t, vMesoscaleCentered);

siteFit = struct( ...
    'siteNumber', siteNumber, ...
    't', t, ...
    'x', x, ...
    'y', y, ...
    'lat0', siteData.lat0, ...
    'f0', 2 * 7.2921e-5 * sin(siteData.lat0*pi/180), ...
    'fit', fit, ...
    'mx', mx, ...
    'my', my, ...
    'sigmaN', sigmaN, ...
    'sigmaS', sigmaS, ...
    'zeta', zeta, ...
    'sigma', sigma, ...
    'thetaDegrees', thetaDegrees, ...
    'uBackground', fit.uBackground(t), ...
    'vBackground', fit.vBackground(t), ...
    'qObserved', qObserved, ...
    'rObserved', rObserved, ...
    'qMesoscale', qMesoscale, ...
    'rMesoscale', rMesoscale, ...
    'observedSpeedRms', sqrt(mean(uObserved.^2 + vObserved.^2, 2)), ...
    'mesoscaleSpeedRms', sqrt(mean(uMesoscale.^2 + vMesoscale.^2, 2)), ...
    'backgroundSpeedRms', sqrt(mean(uBackgroundObserved.^2 + vBackgroundObserved.^2, 2)), ...
    'submesoscaleSpeedRms', sqrt(mean(uSubmesoscale.^2 + vSubmesoscale.^2, 2)));
