function siteFit = loadGriddedStreamfunctionSiteFit(siteNumber)
arguments
    siteNumber (1,1) double {mustBeInteger, mustBeMember(siteNumber, [1 2])}
end

scriptDir = fileparts(mfilename("fullpath"));
dataDir = fullfile(scriptDir, "..", "..", "..", "ExampleData", "LatMix2011");
dataPath = fullfile(dataDir, sprintf("smoothedGriddedRho%dDrifters.mat", siteNumber));
if ~isfile(dataPath)
    error("GriddedStreamfunction:MissingExampleData", ...
        "Expected local example data at %s.", dataPath);
end

siteData = load(dataPath);
t = reshape(siteData.t, [], 1);
x = siteData.x(:, 1:(end - 1));
y = siteData.y(:, 1:(end - 1));
nDrifters = size(x, 2);

fitOptions = legacyAlignedGriddedStreamfunctionFitOptions(t, x, y, 4);
trajectories = TrajectorySpline.empty(0, 1);
for iDrifter = 1:nDrifters
    xSpline = ConstrainedSpline(t, x(:, iDrifter), S=3, knotPoints=fitOptions.fastKnotPoints);
    ySpline = ConstrainedSpline(t, y(:, iDrifter), S=3, knotPoints=fitOptions.fastKnotPoints);
    trajectories(end + 1, 1) = TrajectorySpline.fromComponentSplines(t, xSpline, ySpline); %#ok<AGROW>
end

fit = GriddedStreamfunction(trajectories, psiKnotPoints=fitOptions.psiKnotPoints, ...
    psiS=fitOptions.psiS, fastKnotPoints=fitOptions.fastKnotPoints, fastS=fitOptions.fastS);
xFit = reshape(fit.observedX, numel(t), nDrifters);
yFit = reshape(fit.observedY, numel(t), nDrifters);
diagnostics = griddedStreamfunctionEffectiveDiagnostics(fit, t, xFit, yFit);

sigmaN = fit.sigma_n(t, diagnostics.mxFit, diagnostics.myFit);
sigmaS = fit.sigma_s(t, diagnostics.mxFit, diagnostics.myFit);
zeta = fit.zeta(t, diagnostics.mxFit, diagnostics.myFit);
sigma = sqrt(sigmaN.^2 + sigmaS.^2);
thetaDegrees = unwrap(atan2(sigmaS, sigmaN))/2 * 180/pi;
legacyParameters = EstimateLinearVelocityFieldParameters(x, y, t, [ModelParameter.u0v0, ModelParameter.strain], 4);
legacyReference = struct( ...
    "u0", legacyParameters.u0, ...
    "v0", legacyParameters.v0, ...
    "sigmaN", legacyParameters.sigma_n, ...
    "sigmaS", legacyParameters.sigma_s, ...
    "sigma", hypot(legacyParameters.sigma_n, legacyParameters.sigma_s), ...
    "thetaDegrees", unwrap(atan2(legacyParameters.sigma_s, legacyParameters.sigma_n))/2 * 180/pi);

siteFit = struct( ...
    "siteNumber", siteNumber, ...
    "t", t, ...
    "x", x, ...
    "y", y, ...
    "trajectoryX", xFit, ...
    "trajectoryY", yFit, ...
    "lat0", siteData.lat0, ...
    "f0", 2 * 7.2921e-5 * sin(siteData.lat0*pi/180), ...
    "fit", fit, ...
    "fitOptions", fitOptions, ...
    "timeBasisMatrix", fitOptions.timeBasisMatrix, ...
    "fastKnotPoints", fitOptions.fastKnotPoints, ...
    "fastS", fitOptions.fastS, ...
    "psiKnotPoints", {fitOptions.psiKnotPoints}, ...
    "psiS", fitOptions.psiS, ...
    "mx", diagnostics.mxFit, ...
    "my", diagnostics.myFit, ...
    "mxObserved", diagnostics.mxObserved, ...
    "myObserved", diagnostics.myObserved, ...
    "sigmaN", sigmaN, ...
    "sigmaS", sigmaS, ...
    "zeta", zeta, ...
    "sigma", sigma, ...
    "thetaDegrees", thetaDegrees, ...
    "legacyReference", legacyReference, ...
    "raw", diagnostics.raw, ...
    "uBackground", diagnostics.raw.uBackground, ...
    "vBackground", diagnostics.raw.vBackground, ...
    "qObserved", diagnostics.raw.qObserved, ...
    "rObserved", diagnostics.raw.rObserved, ...
    "qMesoscale", diagnostics.raw.qMesoscale, ...
    "rMesoscale", diagnostics.raw.rMesoscale, ...
    "xBackground", diagnostics.raw.xBackground, ...
    "yBackground", diagnostics.raw.yBackground, ...
    "xMesoscale", diagnostics.raw.xMesoscale, ...
    "yMesoscale", diagnostics.raw.yMesoscale, ...
    "xSubmesoscale", diagnostics.raw.xSubmesoscale, ...
    "ySubmesoscale", diagnostics.raw.ySubmesoscale, ...
    "observedSpeedRms", diagnostics.raw.observedSpeedRms, ...
    "mesoscaleSpeedRms", diagnostics.raw.mesoscaleSpeedRms, ...
    "backgroundSpeedRms", diagnostics.raw.backgroundSpeedRms, ...
    "submesoscaleSpeedRms", diagnostics.raw.submesoscaleSpeedRms);
end
